# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'DaPai' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DaPai
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Moya'
  # pod 'Moya/RxSwift', '~> 13.0'
  pod 'Moya-SwiftyJSONMapper'
  pod 'IQKeyboardManagerSwift'
  pod 'ESPullToRefresh'
  pod 'ObjectMapper', '~> 3.3'
  # 轮播图
  pod 'SBCycleScrollView','~> 0.0.8'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod "ESTabBarController-swift"

  target 'DaPaiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DaPaiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
